-- AlterTable
ALTER TABLE "users" ADD COLUMN     "dayEndHour" INTEGER NOT NULL DEFAULT 22,
ADD COLUMN     "dayStartHour" INTEGER NOT NULL DEFAULT 8,
ADD COLUMN     "defaultView" TEXT NOT NULL DEFAULT 'WEEK',
ADD COLUMN     "hideCompleted" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "timeFormat" TEXT NOT NULL DEFAULT 'H24',
ADD COLUMN     "weekStartsOn" TEXT NOT NULL DEFAULT 'MONDAY';
